### ISSUE TITLE
Very werid problem

### ISSUE THREAD

**Issue by ysef05** [ikz87/dots-2.0#23]
![image](https://user-images.githubusercontent.com/93986222/188327875-bd082bb5-b618-47d6-9711-3def9390f989.png)

as you see in the image werid little boxes i tried to fix it but not luck on the fixes is a reboot 
the cause when i open virtualbox or file manager and do alt-f4 this pops up for some reason 
other fix i tried to do is using feh for the background but no luck..... other fixs is when i use screenshot tool the boxes diappear

**Comment by ysef05** [comment]
here is more clear image 
![image](https://user-images.githubusercontent.com/93986222/188327992-2080cc5c-765c-424e-b6d1-204d20df5709.png)

**Comment by ikz87** [comment]
That's due to the comppositor. [pijulius picom](https://github.com/pijulius/picom) is not super stable at the moment, it has some graphical glitches like the one you're mentioning, which are not something I can fix. To temporarily make the glitch disappear every now and then press `super+p` twice to restart picom.

I personally stopped using pijulius picom in my personal setup, and instead moved to using the window animations branch of [dccsillag's picom](https://github.com/dccsillag/picom/tree/implement-window-animations) which has less options but is way more stable. It's not avialable in the AUR so if you wanna use it you'd have to build it yourself. My current picom configs for dccsillag's picom can be found [here](https://github.com/ikz87/dots-2.0/blob/personal/.config/picom.conf).

**Comment by ikz87** [comment]
Reopening this only to say that I found out there is an AUR package for [dccsillag's picom](https://github.com/dccsillag/picom/tree/implement-window-animations), so now I'm using that instead on the main branch.

Just install [picom-animations-git](https://aur.archlinux.org/packages/picom-animations-git), update `~/.config/picom.conf` to match the current one in the repo and the glitch will be gone (although you'll have some less animations)
