### ISSUE TITLE
Resolution 

### ISSUE THREAD

**Issue by ghost** [ikz87/dots-2.0#25]
Logging in on a new install some widgets are partially offscreen or entirely offscreen.

Is there a way to apply resolutions to correct this?

**Comment by ysef05** [comment]
You will have to go on the config file and edit them to your needs.....

**Comment by ikz87** [comment]
Exactly what @YousefM8 said. I'm guessing you're using a 720p display or something. When writing all of the widgets, I thought of the possibility of using relative sizes with % instead of set sizes with px but that would interfere with some other parts of the rice like font sizes, images, etc. so I just used pixel sizes and set everything for a 1080p screen (since that's what I use).
You'd need to edit specifically `~/.config/wpg/templates/eww_mybar_eww.yuck.base` and ` ~/.config/wpg/templates/eww_mybar_eww.scss.base` and change everything size related to your needs. Wpgtk will apply the changes to the actual eww config files upon restarting the window manager
