### ISSUE TITLE
(Recommended) About lock screen

### ISSUE THREAD

**Issue by awarewen** [ikz87/dots-2.0#27]
Mantablockscreen cannot display lock screen image normally when using multiple screens, while betterlockscreen can work well in the environment of multiple screens

**Comment by ikz87** [comment]
I used mantablockscreen due to it being the fastest and simplest way I could find to have a lock screen that I liked without having to mess around with any i3lock source code, also I never had any issue with it due to only having one monitor. I did know about betterlockscreen, the only thing that kept me from using it was the fact that I couldn't add a profile picture to the lock screen(kinda dumb reason, I know), however your comment made me check BLS repo again and it seems like it's been consistently getting updates, I'll check it out and maybe switch. Thank you for the feedback :)

**Comment by ikz87** [comment]
After trying BSL for a bit again, I still don't like it enough. Now, I think I could just mess around with mantablockscreen and probably make an external script (or just edit ~/.bscripts/lock.sh) to make it display the background correctly on multiple monitors, but I don't have a second monitor to test things out at the moment. Will close the issue but still have this in mind, will fix if I ever get a second monitor

**Comment by awarewen** [comment]
Maybe I will return to mantablockscreen. For the implementation of multiple screens,  refer to here：[i3lock-multimonitor](i3lock-multimonitor/lock at master · ShikherVerma/i3lock-multimonitor)
：））
