### ISSUE TITLE
eww.yuck resets itself

### ISSUE THREAD

**Issue by RinLovesYou** [ikz87/dots-2.0#32]
This is a weird one, I'm just trying to edit eww.yuck to make the bars multi-monitor, and every time i change anything in there, be it eww.yuck or eww.css, it resets itself when i restart bspwm

**Comment by RinLovesYou** [comment]
I think it's just a permission thing

**Comment by RinLovesYou** [comment]
nevermind, even as sudo it still resets itself upon reload

**Comment by ikz87** [comment]
That's because I'm using templates with wpgtk, see [here](https://github.com/deviantfero/wpgtk/wiki/Templates).
Basically, everytime bspwm is reset, wpgtk overwrites both `eww.yuck` and `eww.scss` with wathever is on their template, only replacing the colors so it fits the colorscheme.

To be honest, I didn't implement this very well, since I should have instead made 2 other files (something like `theme.yuck` and `theme.scss`), change the colors there, and just include those files in the bars config. Been trying to implement it that way but I've been busy.

Anyway, for now, instead of editing the file itself, you should edit the templates at `~/.config/wpg/templates/eww_mybar_eww.yuck.base` and `~/.config/wpg/templates/eww_mybar_eww.scss.base` and your changes will be applied on reload. Quick guide on templates: 
```
{color8} will be replaced with the 8th color on your colorscheme 
{active} will be replaced with the "active color" on your colorscheme

if you have normal braces {{
   you will need to escape them like this
}}

but this means you can do things like: 
{color8}                -> #ffffff
{color8.octal}          -> #77777777
{active.rgb}            -> 255, 255, 255
{userdefinedcolor.rgb}  -> 0, 0, 0
#BA{color8.strip}       -> #BAffffff
```

Run `wpg` and go to the templates tab, there you will have a quick access to every template included in the repo if you wanna edit any other colorscheme dependant config files.
![image](https://user-images.githubusercontent.com/98569017/212969118-5e5b6e47-5b13-4029-b08b-2fc1b392bd7b.png)

**Comment by ikz87** [comment]
Wanted to add, I just pushed a better implementation of eww templates. If you update (update the repo and run install.sh again) you can edit the files directly since wpgtk doesn't overwrite them anymore. 
Let me know how it goes if you do so.

**Comment by RinLovesYou** [comment]
Oh wow yeah, i never managed to find those template files on my own, thank you very much!
