### ISSUE TITLE
Login/Lock screen

### ISSUE THREAD

**Issue by the-merky** [ikz87/dots-2.0#38]
I always just boot into a tty1 and need to login and then run startx. Is there a way to automate this?

**Comment by ikz87** [comment]
Yes, kinda.
I don't think it's necessarily a good idea to "automatically" log into your user when booting your PC because that would mean your machine is not protected in the case someone else gets their hands on it, but I know that tty's look ugly so I can kinda see where you're coming from.

A way you can skip seeing a tty is using a [display manager](https://wiki.archlinux.org/title/display_manager), I would recommend [sddm](https://github.com/sddm/sddm) since you can make it look quite good with some work.

Here's how to set it up:

1- Install it 
```
yay -Sy sddm
```

2- Enable and start the service (the commands below will only work if you're using [systemd](https://wiki.archlinux.org/title/systemd), which you likely are)
```
systemctl enable sddm
systemctl start sddm
```
You will be asked to enter your password for each command.

After that (and a bit of waiting) you should see something like this but with a different theme:

<p align="center">
  <img src="https://user-images.githubusercontent.com/98569017/224471597-1890ab9c-117f-45d6-a8fa-da9c0d05261e.png"</img>
  <small>(Sorry for the quality, don't know how to take actual screenshots here)</small>
</p>

Then somewhere in your screen there should be some text saying "Desktop session". You should be able to just click there and select `bspwm` (in case that's not the default option). Then when you log in with the display manager, `bspwm` will be executed.

But if what you want to skip is just writing `startx` after login in a tty, you can instead append the following to your `.bashrc`:
```
# Run Xorg                                                                              
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    exec startx
else
```
The above will make Xorg run automatically everytime you login in tty1 specifically.

Now, if you want to completely skip login you can use [xlogin](https://github.com/joukewitteveen/xlogin), but from my own experience, I'd say it tends to not work from time to time. In that case you can make a systemd service yourself using [agetty](https://wiki.archlinux.org/title/getty#Automatic_login_to_virtual_console) which Is how I personally do it.

Lastly, if you are skipping login, please protect your pc by at least prompting for a password when `bspwm` starts, I do it by launching `~/.bscripts/lock.sh` as soon as the window manager starts.

Does this answer your question?

(Just finished writing this to see you marked the issue as completed lol, still this info might be useful so it's fine)

**Comment by ikz87** [comment]
Alright, reopening now. I'm guessing you just want a display manager running. 

Let me know if you managed to get `sddm` working, will close the issue when you do

**Comment by the-merky** [comment]
Yeah I got it fixed. Sorry I opened another duplicate issue, the other one vanished from my mobile app...
