### ISSUE TITLE
Help with eww ?

### ISSUE THREAD

**Issue by stuff97** [ikz87/dots-2.0#6]
Hello dev,

Managed to get your rice running on arch but I couldn't get eww to display correctly, I guess the rice was make for 1080p and I'm running 1440p display. I've also install `sysstat` package for system statistics but they're not getting updated so far.

I'm also not sure what font you used, since as you can see bellow a lot of icons are missing.

I've literally no experience using eww, so a little help is appreciated.

Edit: got the stats running by making the scripts under `~/.config/eww/mybar/script` executable, `chmod u+x ~/.config/eww/mybar/script/*`

**Comment by ikz87** [comment]
Hey, thanks for checking out the repo.

First of all, yes, the bar is configured to be used in a 1080p display, I don't have access to a 1440p one so you'd have to mess with the geometry property for the windows on your own, they're at line 56 in .config/eww/mybar/eww.yuck 
I'd recommend making the central bar a little wider and then moving the right bar further to the right because the widgets on the central bar will be automatically centered and you won't have to change anything in the eww.scss file.

As for the fonts, I used Nova Mono for almost everything, and Hack specifically for the workspace icons in the left bar.

Good luck and let me know if you manage to get everything working fine :)

**Comment by stuff97** [comment]
Managed to get eww to scale correctly, but I still have the icons issue as you can see bellow:

![2022-08-16_15-38](https://user-images.githubusercontent.com/61669101/184907681-dec3d100-3393-4295-b098-defcd9e7fc6b.png)
![2022-08-16_00-44](https://user-images.githubusercontent.com/61669101/184907694-26b8cb2e-d1b1-4e33-92b8-f2f52dda28d4.png)

Installed `ttf-nova` and `ttf-hack` but to avail so far.

Edit: noticed that eww is not changing color scheme when `wallset` is used, not sure if that has anything to do with `~/.config/polybar` config files missing ?

**Comment by ikz87** [comment]
It seems like the fonts you installed aren't working correctly, I'd suggest downloading and installing them manually from:
- Nova mono: https://fonts.google.com/specimen/Nova+Mono?query=nova+mono
- Hack: https://github.com/source-foundry/Hack
Also, I noticed some of the icons seem to be coming from another font I have installed in my system.
Font Awesome: https://fontawesome.com/download

Now, for the wallset stuff, it shouldn't have enything to do with polybar. 
First of all, have you installed wpgtk yet? https://github.com/deviantfero/wpgtk
It's what I use to give a global colorscheme for all my rice.
All the wallset script does is:
- Copies the image you give it to ~/Pictures/Important/wallpaper.png (create the directory if it doesn't exist yet)
- Restarts bspwm
Then, in the first few lines in .config/bspwm/bspwmrc I update the colors with `wpg -R; wpg -s`
The wpgtk part of my rice is quite messy, I recommend you read the wiki on wpgtk's repo so you can understand more about how it works, that way you can even extend it to more programs if you want to!

**Comment by ikz87** [comment]
Btw since I'm not 100% about how wpgtk works with its config file (which is included in my repo) be sure to check you have the following templates, otherwise it will not change anything
![2022-08-16_11-03](https://user-images.githubusercontent.com/98569017/184937237-5114f00c-58b1-4624-9dfb-fb61e7cc9370.png)

**Comment by stuff97** [comment]
I'll try to get everything sorted as soon as I have some free time (probably by tomorrow), I'll let you know if I managed to get stuff together.

**Comment by stuff97** [comment]
Hello again dev,

I finally managed to setup every thing as I intended, thank you very much for this amazing rice. I'm really happy with how it ended up looking, gorgeous setup.

Thank you, regards,
